# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.03.23

# Minecraft
minecraft_version=1.21.4
minecraft_version_range=[1.21.4]

# NeoForge
neo_version=21.4.0-beta
neo_version_range=[21.4.0-beta,21.5.0-beta)
loader_version_range=[1,)

# Mod properties
mod_id=commontrades
mod_name=Common Trades
mod_license=MIT License
mod_version=1.0.0
mod_group_id=de.artemis.commontrades
mod_authors=DoomedArtemis
mod_description=Automatically adds suitable modded items to Wandering Trader trades for seamless modpack integration.
