# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)

# Forge
forge_version=36.2.42
forge_version_range=[36.2.0,37)
loader_version_range=[36,)

# Mod properties
mod_id=commontrades
mod_name=Common Trades
mod_license=MIT License
mod_version=1.0.0
mod_group_id=de.artemis.commontrades
mod_authors=DoomedArtemis
mod_description=Automatically adds suitable modded items to Wandering Trader trades for seamless modpack integration.
